ScriptAliasMatch ^/mercurial(.*) /mercurial/hgweb.cgi$1
<Directory "/mercurial/">
Options Indexes FollowSymlinks MultiViews ExecCGI
AllowOverride All
Order allow,deny
Allow from all
AuthType Basic
AuthName "Mercurial Repositories"
AuthUserFile /mercurial/hgusers
Require valid-user
</Directory>
