ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab01
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab02
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab03
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab04
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab05
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab06
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab07
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab08
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab09
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab10
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab11
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab12
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab13
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab14
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab15
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab16
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab17
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab18
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab19
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab20
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab21
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab22
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab23
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab24
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab25
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab26
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab27
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab28
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab29
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab30
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab31
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab32
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab33
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab34
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab35
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab36
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab37
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab38
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab39
ssh-keygen -f "/home/jbreslin/.ssh/known_hosts" -R lab40
clusterssh student@lab01 student@lab02 student@lab03 student@lab04 student@lab05 student@lab06 student@lab07 student@lab08 student@lab09 student@lab10 student@lab11 student@lab12 student@lab13 student@lab14 student@lab15 student@lab16 student@lab17 student@lab18 student@lab19 student@lab20 student@lab21 student@lab22 student@lab23 student@lab24 student@lab25 student@lab26 student@lab27 student@lab28 student@lab29 student@lab30 student@lab31 student@lab32 student@lab33 student@lab34 student@lab35 student@lab36 student@lab37 student@lab38 student@lab39 student@lab40
