creative_mode = true
enable_damage = false
enable_shaders = true
fixed_map_seed = 
main_menu_last_game_idx = 1
main_menu_tab = server
mainmenu_last_selected_world = 1
max_users = 23
mg_name = v6
name = student
port = 30000
selected_world_path = /home/jbreslin/.minetest/worlds/vizocraft
server_dedicated = false
fast_move = true
free_move = true
noclip = false
address = 192.168.2.150
remote_port = 30000
server_announce = true
